# Generated by Django 3.0 on 2023-08-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mgrprofile',
            name='mgr',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rbloc',
        ),
        migrations.AlterField(
            model_name='booking',
            name='rbtype',
            field=models.CharField(choices=[('0', '---Select Room Type---'), ('1', '1-Adult/Room'), ('2', '2-Adults/Room')], default='0', max_length=10),
        ),
        migrations.DeleteModel(
            name='GstProfile',
        ),
        migrations.DeleteModel(
            name='MgrProfile',
        ),
    ]
