# Generated by Django 3.0 on 2023-08-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_auto_20230810_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role1',
            field=models.CharField(choices=[('Guest', 'Guest'), ('User', 'User'), ('Staff', 'Staff')], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='role2',
            field=models.CharField(choices=[('0', '---Select Staff Type---'), ('Receptionist', 'Receptionist'), ('House Keeping', 'House Keeping'), ('Porter', 'Porter'), ('Restaurant Staff', 'Restaurant Staff')], default='0', max_length=20),
        ),
    ]
