# Generated by Django 3.0 on 2023-08-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0003_auto_20230810_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pfupd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rbtype',
            field=models.CharField(choices=[('0', '---Select Room Type---'), ('1A', '1-Adult/Room(AC)'), ('2A', '2-Adults/Room(AC)'), ('1N', '1-Adult/Room(Non-AC)'), ('2N', '2-Adults/Room(Non-AC)')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role1',
            field=models.CharField(choices=[('Guest', 'Guest'), ('User', 'User'), ('Staff', 'Staff')], default='Guest', max_length=10),
        ),
    ]
