# Generated by Django 3.0 on 2023-08-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rnum',
            field=models.CharField(default='', max_length=10),
        ),
    ]
