# Generated by Django 3.0 on 2023-08-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0007_booking_rnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amt',
            field=models.CharField(default='', max_length=10),
        ),
    ]
