# Generated by Django 3.0 on 2023-08-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0008_booking_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payatch',
        ),
    ]
