# Generated by Django 3.0 on 2023-08-15 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0010_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stn', models.CharField(max_length=20)),
                ('sttp', models.CharField(choices=[('0', '---Select Staff Type---'), ('Receptionist', 'Receptionist'), ('House Keeping', 'House Keeping'), ('Porter', 'Porter'), ('Restaurant Staff', 'Restaurant Staff')], default='0', max_length=20)),
                ('salary', models.CharField(max_length=10)),
                ('crsal', models.CharField(max_length=20)),
                ('st', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
