# Generated by Django 3.0 on 2023-08-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0011_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
