# Generated by Django 3.0 on 2023-08-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0012_staff_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtp', models.CharField(choices=[('0', '---Select Room Type---'), ('1A', '1-Adult/Room(AC)'), ('2A', '2-Adults/Room(AC)'), ('1N', '1-Adult/Room(Non-AC)'), ('2N', '2-Adults/Room(Non-AC)')], default='0', max_length=10)),
                ('rfee', models.CharField(max_length=10)),
            ],
        ),
    ]
