# Generated by Django 3.0 on 2023-09-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0014_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
