from django.urls import path
from .views import *
from django.contrib.auth import views as vie

urlpatterns=[
    path('',home,name="hm"),
    path('about/',about,name="abt"),
    path('contact/',contact,name="cnt"),
    path('register/',register,name="reg"),
    path('login/',vie.LoginView.as_view(template_name='html/login.html'),name="log"),
    path('logout/',vie.LogoutView.as_view(template_name='html/logout.html'),name="logt"),
    path('userlist/',userlist,name="usrl"),
    path('delete/<int:t>/',delete,name="del"),
    path('update/<int:d>/',update,name="upd"),
    path('profile/',profile,name="pfle"),
    path('updprofile/',updprofile,name="updpf"),
    path('mail/',mailsend,name="ml"),
    path('dashboard/',dashboard,name="dshbd"),
    path('booking/<int:b>/',booking,name="book"),
    path('prices/',prices,name="pr"),
    path('rblist/',rblist,name="rbl"),
    path('rbupdate/<int:u>/',rbupdate,name="rbup"),
    path('rbdelete/<int:d>/',rbdelete,name="rbdel"),
    path('grupdate/<int:g>/',grupdate,name="grup"),
    path('prevbookings/',prevbookings,name="prevbook"),
    path('changepass/',changepass,name="chpass"),
    path('duty/',duty,name="dt"),
    path('feedback/',feedback,name="fd"),
    path('prevfb/',prevfb,name="pfb"),
    path('givefb/',givefb,name="gfb"),
    path('stffb/',stafffb,name="sfb"),
    #path('fdup/<int:z>/',updfb,name="ufb"),
    path('fbdel/<int:z>/',delfb,name="dfb"),
    path('salary/',salary,name="sl"),
    path('roomnum/',roomnum,name="rn"),
    path('fee/',fee,name="fee"),
    path('pay/',payment,name="py"),
    path('allpay/',allpayments,name="apy"),
    path('staff/',staff,name="staff"),
    path('updsal/<int:d>/',updsalary,name="ups"),
    path('crdsal/<int:d>/',crdsalary,name="cs"),
    path('rooms/',rooms,name="rmd"),
    path('dates/',dates,name="dat"),
    path('rmfee/',roomfee,name="rfe"),
]